server:
  port: 6065

spring:
  application:
    name: ms-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/notbutter17/ultimochance.git
          searchPaths:
            - jgt-config-data
          default-label: main

  security:
    user:
      name: root
      password: